### ISSUE TITLE
ユースケース：掲示板作成の修正

### ISSUE THREAD

**Issue by kbc16a03** [GroupConnect/GroupConnect#39]
- [ ] 1. 概要の修正

- [ ] 2. 代替フローの修正

- [ ] 3. 例外フローの修正

[掲示板作成](../wiki/ユースケース：掲示板作成)

1について
ユーザーをユーザに修正。

2について
見出しが表示されてしまっているので修正すること。
3. 4. 1. の項目2に基本フロー7に戻るを追加する。

3について
見出しが表示されてしまっているので修正すること。

**Comment by CyberTorte** [comment]
- [ ] 4. 基本フロー1の修正

- [ ] 5. 代替フローの修正

- [ ] 6. 例外フローの修正

4について
マイページにあるを追記することで
読みやすくなるので追記すること。

5について
代替フローでユースケースを終了してしまうと
事後条件を満たせない。
修正すること。

6について
恐らく6のケースだと
基本フロー6に戻れない。
削除すること。
